name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Change directory
        run: cd web

      - name: Install dependencies
        run: |
          cd web
          yarn install --frozen-lockfile

      - name: Copy env
        run: |
          cd web
          cp .env .env.local

      - name: Build
        run: |
          cd web
          yarn build

      - name: Replace assets paths
        run: |
          cd web/dist
          sed -i 's|src="/|src="https://unpkg.com/portalbbs@1.0.2/|g' index.html
          sed -i 's|href="/|href="https://unpkg.com/portalbbs@1.0.2/|g' index.html
          sed -i 's|url(/|url(https://unpkg.com/portalbbs@1.0.2/|g' index.html

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./web/dist
          cname: bbs.portalapi.site
