name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    name: Build & Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.22"

      - name: Install dependencies
        run: go mod download

      - name: Build linux-arm64
        run: make linux-arm64

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: paopao-release
          path: release/*.zip

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: release/*.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}